version:
  tag:    'v{version.major}.{version.minor}.{version.patch}'
  format: semver
  bump:
    policy: conventional-commits
    strict: yes

scm:
  git:
    worktrees:
      doc/build/html: pages

phases:
  style:
    commit-messages:
      - python3 -m virtualenv --clear venv
      - venv/bin/python -m pip install --upgrade 'commisery>=0,<1'
      # Require each commit message to adhere to our requirements
      - foreach: AUTOSQUASHED_COMMIT
        sh: venv/bin/python venv/bin/commisery-verify-msg ${AUTOSQUASHED_COMMIT}
      - venv/bin/python venv/bin/commisery-verify-msg HEAD

  test:
    python3.6:
      - junit: junit-test.xml
        image: python:3.6
        volumes:
          - /usr/bin/docker:/usr/bin/docker:ro
          - ${WORKSPACE}/.local:~/.local
      - python -m pip install --user --upgrade virtualenv
      - python -m virtualenv --clear venv3.6
      - venv3.6/bin/python setup.py pytest

    python3.7:
      - junit: junit-test.xml
        image: python:3.7
        volumes:
          - /usr/bin/docker:/usr/bin/docker:ro
          - ${WORKSPACE}/.local:~/.local
      - python -m pip install --user --upgrade virtualenv
      - python -m virtualenv --clear venv3.7
      - venv3.7/bin/python setup.py pytest

  build:
    sphinx-doc:
      - rm -rf doc/build/venv
      - python3 -m virtualenv --clear doc/build/venv
      - doc/build/venv/bin/python -m pip install setuptools_scm setuptools_scm_git_archive . -r doc-requirements.txt
      - archive:
          artifacts: doc/build/html/**
        worktrees:
          doc/build/html:
            commit-message: "Update documentation for ${VERSION}"
        sh: sh -c 'doc/build/venv/bin/python -m sphinxcontrib.versioning build --override-branch=${GIT_BRANCH}=${GIT_COMMIT} doc/source doc/build/html && find doc/build/html -name .doctrees -exec rm -r "{}" +'
