version:
  tag:    'v{version.major}.{version.minor}.{version.patch}'
  format: semver
  bump:
    policy: conventional-commits
    on-every-change: no
    strict: yes

scm:
  git:
    worktrees:
      doc/build/html: pages

pass-through-environment-vars:
  - GIT_COMMITTER_NAME
  - GIT_COMMITTER_EMAIL

modality-source-preparation:
  AUTO_MERGE:
    - git fetch origin release/1
    - sh: git merge --no-commit --no-ff FETCH_HEAD
      changed-files: []
      commit-message: "Merge branch 'release/1'"

phases:
  style:
    commit-messages: !template "commisery"

  test:
    python3.6:
      - docker build --build-arg=PYTHON_VERSION=3.6 -t hopic-python:3.6-slim-git hopic/test/docker-images/python
      - junit: junit-test.xml
        image: hopic-python:3.6-slim-git
        docker-in-docker: yes
        volumes:
          - ${WORKSPACE}/.local:~/.local
      - python3.6 -m venv --clear venv3.6
      - venv3.6/bin/python setup.py pytest

    python3.7:
      - docker build --build-arg=PYTHON_VERSION=3.7 -t hopic-python:3.7-slim-git hopic/test/docker-images/python
      - junit: junit-test.xml
        image: hopic-python:3.7-slim-git
        docker-in-docker: yes
        volumes:
          - ${WORKSPACE}/.local:~/.local
      - python3.7 -m venv --clear venv3.7
      - venv3.7/bin/python setup.py pytest

    python3.8:
      - docker build --build-arg=PYTHON_VERSION=3.8 -t hopic-python:3.8-slim-git hopic/test/docker-images/python
      - junit: junit-test.xml
        image: hopic-python:3.8-slim-git
        docker-in-docker: yes
        volumes:
          - ${WORKSPACE}/.local:~/.local
      - python3.8 -m venv --clear venv3.8
      - venv3.8/bin/python setup.py pytest

  build:
    sphinx-doc:
      - rm -rf doc/build/venv
      - python3 -m venv --clear doc/build/venv
      - doc/build/venv/bin/python -m pip install setuptools_scm setuptools_scm_git_archive . -r doc-requirements.txt
      - archive:
          artifacts: doc/build/html/**
        worktrees:
          doc/build/html:
            commit-message: "Update documentation for ${VERSION}"
        sh: >
          sh -c 'doc/build/venv/bin/python -m sphinxcontrib.versioning build --override-branch=${GIT_BRANCH}=${GIT_COMMIT} doc/source doc/build/html
          && find doc/build/html \( -name .doctrees -o -name objects.inv \) -exec rm -r "{}" +'
