version:
  tag:    'v{version.major}.{version.minor}.{version.patch}'
  format: semver
  bump:
    policy: conventional-commits
    on-every-change: no

scm:
  git:
    worktrees:
      doc/build/html: pages

phases:
  style:
    commit-messages:
      - python3 -m pip install --user --upgrade 'stemming>=1,<2' regex
      # Require each commit message to adhere to our requirements
      - foreach: AUTOSQUASHED_COMMIT
        sh: .ci/verify-commit-message.py ${AUTOSQUASHED_COMMIT}
      - .ci/verify-commit-message.py HEAD

  test:
    python:
      - python3 -m virtualenv --clear venv
      - venv/bin/python setup.py pytest
      - junit: junit-test.xml

  build:
    sphinx-doc:
      - rm -rf doc/build/venv
      - python3 -m virtualenv --clear doc/build/venv
      - doc/build/venv/bin/python -m pip install setuptools_scm setuptools_scm_git_archive . -r doc-requirements.txt
      - archive:
          artifacts: doc/build/html/**
        worktrees:
          doc/build/html:
            commit-message: "Update documentation for ${VERSION}"
        sh: sh -c 'doc/build/venv/bin/python -m sphinxcontrib.versioning build --override-branch=${GIT_BRANCH}=${GIT_COMMIT} doc/source doc/build/html && find doc/build/html -name .doctrees -exec rm -r "{}" +'
