[build-system]
requires = [
  "setuptools >= 40.9.0",
  "setuptools_scm",
  "setuptools_scm_git_archive",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
include = "hopic"
line-length = 160
target-version = ["py36", "py39"]
